import socket
import time
import os
name = input('Enter your name: ')
print('')
time.sleep(1)
password = input('Enter your password: ')
time.sleep(1)
print('')
print('loading...')
time.sleep(2)
os.system('clear')
print('\033[96mYOUR NAME IS:',name)
print('')
time.sleep(1)
print('\033[93mYOUR PASSWORD IS:',password)
print('')
ip = socket.gethostbyname(socket.gethostname())
time.sleep(2)
print('\033[95mYOUR IP:',ip)
print('')
host = socket.gethostname()
time.sleep(2)
print('\033[90mYOUR HOST:',host)